name: Build ThunderInterfaces on Linux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # change the user and branch name in each one after the templates are merged
  Thunder:
    uses: VeithMetro/Thunder/.github/workflows/Linux build template.yml@development/actions

  ThunderInterfaces:
    needs: Thunder
    uses: VeithMetro/ThunderInterfaces/.github/workflows/Linux build template.yml@development/actions

  ThunderClientLibraries:
    needs: ThunderInterfaces
    uses: VeithMetro/ThunderClientLibraries/.github/workflows/Linux build template.yml@development/actions

  ThunderNanoServices:
    needs: ThunderInterfaces
    uses: VeithMetro/ThunderNanoServices/.github/workflows/Linux build template.yml@development/actions

  ThunderNanoServicesRDK:
    needs: ThunderInterfaces
    uses: VeithMetro/ThunderNanoServicesRDK/.github/workflows/Linux build template.yml@development/actions
