name: MacOS build template

on:
  workflow_call:

jobs:
  Thunder:
    runs-on: macos-14

    strategy:
      matrix:
        build_type: [Debug, Release, MinSizeRel]
        shared_libs: [ON, OFF]

    name: Build type - ${{matrix.shared_libs == 'OFF' && 'Static ' || ''}}${{matrix.build_type}}
    steps:
# --------- Installing packages & downloading artifacts ---------
    - name: Install necessary packages
      run: |
          brew update
          brew upgrade
          brew install ninja zlib
          python3 -m venv my_venv
          source my_venv/bin/activate
          pip install jsonref

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: Thunder-${{matrix.build_type}}-artifact
        path: ${{matrix.build_type}}

    - name: Unpack files
      run: |
        tar -xvzf ${{matrix.build_type}}/${{matrix.build_type}}.tar.gz
        rm ${{matrix.build_type}}/${{matrix.build_type}}.tar.gz

# ----- Checkout & DependsOn regex -----
    - name: Checkout ThunderInterfaces - default
      if: ${{ !contains(github.event.pull_request.body, '[DependsOn=ThunderInterfaces:') }}
      uses: actions/checkout@v4
      with:
        path: ThunderInterfaces
        repository: rdkcentral/ThunderInterfaces
        ref: development/Actions-macOS # change to master

    - name: Regex ThunderInterfaces
      if: contains(github.event.pull_request.body, '[DependsOn=ThunderInterfaces:')
      id: thunderinterfaces
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '(?<=\[DependsOn=ThunderInterfaces:).*(?=\])'
        regex_flags: 'gim'
        search_string: ${{github.event.pull_request.body}}

    - name: Checkout ThunderInterfaces - ${{steps.thunderinterfaces.outputs.first_match}}
      if: contains(github.event.pull_request.body, '[DependsOn=ThunderInterfaces:')
      uses: actions/checkout@v4
      with:
        path: ThunderInterfaces
        repository: rdkcentral/ThunderInterfaces
        ref: ${{steps.thunderinterfaces.outputs.first_match}}

# ----- Building & uploading -----
    - name: Build ThunderInterfaces
      run: |
        source my_venv/bin/activate
        cmake -G Ninja -S ThunderInterfaces -B ${{matrix.build_type}}/build/ThunderInterfaces \
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror" \
        -DCMAKE_C_FLAGS="-Wall -Wextra -Wpedantic -Werror" \
        -DCMAKE_INSTALL_PREFIX="${{matrix.build_type}}/install/usr" \
        -DCMAKE_MODULE_PATH="${PWD}/${{matrix.build_type}}/install/usr/include/WPEFramework/Modules"
        cmake --build ${{matrix.build_type}}/build/ThunderInterfaces --target install

    - name: Tar files
      run: tar -czvf ${{matrix.build_type}}.tar.gz ${{matrix.build_type}}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ThunderInterfaces-${{matrix.build_type}}-artifact
        path: ${{matrix.build_type}}.tar.gz
